import {
  LucideIcon,
  Croissant,
  ChartNoAxesCombined,
  Home,
  List,
  FileText,
  Coffee,
  Pizza,
  Cookie,
  Cake,
  Cross,
  Users,
  BicepsFlexed,
  BriefcaseBusiness,
  Anchor,
  House,
  Binary,
  DollarSign,
  Calendar,
  GraduationCap,
  ListCheck,
  BookOpen,
  Code,
  Church,
  Heart,
  Dumbbell,
  BugIcon,
  Lightbulb,
  SquarePlus,
  CirclePlus,
  TrendingUp,
  TestTubeDiagonal,
  Rocket,
  SquareChartGantt,
  Pencil,
  NotebookPen,
  Phone,
  Headphones,
  Send,
  Brush,
  Mail,
  Text,
  Bed,
} from "lucide-react";

export const dashboardLink = {
  href: "/dashboard",
  label: "Dashboard",
  icon: Home,
};

export const generalLinks = [
  { href: "/tasks", label: "Tasks", icon: List },
  { href: "/notes", label: "Notes", icon: FileText },
];

export const workspaceLinks: Record<
  string,
  Array<{ href: string; label: string; icon: LucideIcon }>
> = {
  DEFAULT: [],
  DEVELOPMENT: [{ href: "/projects", label: "Projects", icon: Binary }],
  FAITH: [
    { href: "/bible-studies", label: "Bible Studies", icon: BookOpen },
    { href: "/prayers", label: "Prayers", icon: ListCheck },
    { href: "/sermons", label: "Sermons", icon: FileText },
  ],
  FINANCE: [
    { href: "/budget", label: "Budget", icon: DollarSign },
    { href: "/finance/schwab", label: "Schwab", icon: ChartNoAxesCombined },
  ],
  HEALTH: [
    { href: "/workouts", label: "Workouts", icon: Dumbbell },
    { href: "/sleep", label: "Sleep", icon: Bed },
  ],
  SCHOOL: [{ href: "/courses", label: "Courses", icon: GraduationCap }],
  WORK: [{ href: "/projects", label: "Projects", icon: BriefcaseBusiness }],
  BLOG: [{ href: "/posts", label: "Posts", icon: Text }],
};

export const ICON_MAP: Record<string, LucideIcon> = {
  Anchor,
  BicepsFlexed,
  Bed,
  Binary,
  BriefcaseBusiness,
  Brush,
  BugIcon,
  Cake,
  CirclePlus,
  Church,
  Code,
  Coffee,
  Cookie,
  Croissant,
  Cross,
  DollarSign,
  Dumbbell,
  Headphones,
  Heart,
  House,
  Lightbulb,
  Mail,
  NotebookPen,
  Pencil,
  Phone,
  Pizza,
  Rocket,
  Send,
  SquareChartGantt,
  SquarePlus,
  TestTubeDiagonal,
  TrendingUp,
  Users,
};
