name: Deploy Production

on:
  push:
    branches:
      - 'main'

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  DIRECT_URL: ${{ secrets.DIRECT_URL }}
  TIPTAP_PRO_TOKEN: ${{ secrets.TIPTAP_PRO_TOKEN }}
  NEXT_PUBLIC_BUILD_TIME: ${{ format('{0:yyyy-MM-ddTHH:mm:ssZ}', github.event.repository.updated_at) }}
  NEXT_PUBLIC_APP_VERSION: ${{ fromJSON(inputs.package-json).version }}

jobs:
  deploy-production:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure TipTap Pro Registry
        run: |
          npm config set "@tiptap-pro:registry" https://registry.tiptap.dev/
          npm config set "@tiptap-cloud:registry" https://registry.tiptap.dev/
          npm config set "//registry.tiptap.dev/:_authToken" ${{ env.TIPTAP_PRO_TOKEN }}

      - name: Run Prisma Migrate
        run: |
          npx prisma generate
          npx prisma migrate deploy

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}